<a href="https://colab.research.google.com/github/slowanimals/D2L/blob/main/Ch_2_Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch==2.0.0 torchvision==0.15.1
!pip install d2l==1.0.3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 76.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 78.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 69.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 42.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 168.4/168.4 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.6/54.6 MB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 102.6/102.6 MB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.2/173.2 MB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.1/177.1 MB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9

In [3]:
import torch

## **Populating Tensors**

In [28]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [32]:
z = torch.zeros(12)
z

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
o = torch.ones(12)
o

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
r = torch.randn(3,4)
r

torch.randn: tensor([[ 0.9728, -0.0931, -0.4151,  1.1767],
        [-0.2778, -0.1625,  0.1738,  0.0196],
        [ 2.4929, -0.5078, -1.0611, -0.1952]])


In [33]:
t = torch.tensor([[2, 1, 4, 3],
                  [3, 2, 1, 5],
                  [6, 7, 8, 9]])
t

tensor([[2, 1, 4, 3],
        [3, 2, 1, 5],
        [6, 7, 8, 9]])

# **Finding Properties**


In [35]:
print(x.numel())
print(x.shape)
print(x.reshape(3,4))

12
torch.Size([12])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [42]:
k = torch.arange(12,dtype=torch.float32).reshape(3,4)
print(k)
k[:2,:] = 13
print(k)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [ 8.,  9., 10., 11.]])


In [45]:
x = torch.tensor([0,1,2,3])
e = torch.exp(x)
e

tensor([ 1.0000,  2.7183,  7.3891, 20.0855])

In [47]:
y = torch.tensor([4,5,2,7])
b = x == y
b

tensor([False, False,  True, False])

In [49]:
print(x + y)
print(x * y)
print(x.sum())

tensor([ 4,  6,  4, 10])
tensor([ 0,  5,  4, 21])
tensor(6)


# **Conversion to Other Python Objects**

In [55]:
X = torch.arange(5, dtype=torch.int32)
A = X.numpy() #numpy array
B = torch.from_numpy(A) #back to torch
B

tensor([0, 1, 2, 3, 4], dtype=torch.int32)

In [56]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)